---
plugins:
  - stylelint-scss
  - stylelint-declaration-block-no-ignored-properties
  - stylelint-no-unsupported-browser-features
extends:
  - stylelint-config-recommended-scss
  - stylelint-prettier/recommended
  # plugin rules
  plugin/declaration-block-no-ignored-properties: true
  plugin/no-unsupported-browser-features:
    - true
    - browsers: [
      "> 5% in JP",
      "Last 2 Safari versions",
      "Last 2 iOS versions",
      "Last 2 Chrome versions",
      "Last 2 ChromeAndroid versions",
      "IE 11",
      "Last 2 Edge versions",
      "Last 2 Firefox versions",
      "Last 2 FirefoxAndroid versions",
      ]
    - severity: "warning"